services:
  consul:
    image: hashicorp/consul:1.18
    container_name: consul
    ports:
      - "8500:8500"
    volumes:
      - ./consul/config.json:/consul/config/config.json
    command: consul agent -dev -client=0.0.0.0 -config-file=/consul/config/config.json
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - app-network

  postgres-auth:
    image: postgres:15-alpine
    container_name: postgres-auth
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: authdb
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autopresale
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      CONSUL_ADDRESS: consul:8500
      JWT_SECRET: "your-secret-key-change-in-production"
      AUTH_SERVICE: "auth-service"
    depends_on:
      - consul
    volumes:
      - ../api-gateway/config.yaml:/app/config.yaml
    networks:
      - app-network

  mock-service:
    build:
      context: ../mock-service
      dockerfile: Dockerfile
    container_name: mock-service
    ports:
      - "8081:8081"
    environment:
      PORT: "8081"
      CONSUL_ADDRESS: consul:8500
    depends_on:
      - consul
    networks:
      - app-network

  auth-service:
    build:
      context: ../AuthService/AuthService
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "5158:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-auth;Port=5432;Database=authdb;Username=postgres;Password=1234
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Issuer=AuthService
      - Jwt__Audience=ApiClients
      - Jwt__AccessTokenLifetimeMinutes=30
      - Jwt__RefreshTokenLifetimeDays=7
      - Jwt__PrivateKey=MIIEpQIBAAKCAQEAy3wuQ1UkUrcEaxR+1gVEEUigRdJthoFenMC/BhpB7y5pelrpoNxdHhAWDuHwOYvj70ZuRxlf2I5Gl+nuVTFQG0P7uS7coVT2zcrzBZp5WNs5LzWea2f5GyFOCtFeXH4fMqfIJdJs+y8+o2luQx4OdZkPJ9sTuRTywDEd92smwY0kqAtLa1ejuFmvB207qCJNKYgvYpgDXdYA5tgZxtepozTTbEBkYk14XETmK2GOgIR3B8PixfEFM2EK6oIqrtKEh020h1FiYVZNWlDmvpwWJxgNoaDoCvAay7jGDwn76Gu8rqTkkHaodNZ5QPasHuk6xqhnMCcYh2NBo9+rV290rQIDAQABAoIBAQCVGMR9KaGXyeo+26GkB++8Ck8FWg5Og/RjPwe43Px62LMIqByPdWf1YywGc56lS88Tv7OF/R2xe25WWV38pklf8Qw8wA2BWNQOLiqrbGiFpvvbj5oocOKh8mFQo+BUPUV2xGFu9SRNWGy5J8NXAmrt19y3A1sMPkEweczPQYAASLCYZP3gVHP2d3aaoXX8BXBTGABZTp01TooxQmu2FP9UbQl7/nwjQ8QzP1sENx4zSGe4oaQI4ejn35q9vB29y8rH4v4EmmmuQQJqVScizyUJvz/lVA9tltx/itMgauiWYY/JHUFphO72cIRhIP1tvYeM0ZP0M8jBHmBmiEjrbcCxAoGBAOF9Z+BLDuUrrQ0/sCFrM6KjfugRo4mzJacLTAzMj9BaCWdzWiZd24K9l2JGZOj+oQmCZOYi3NldLIhFPXj9E2KSdnKSs0NuzjMg9fjaNwzAcy1SSIBxf5CPMS78lERU2rjblxlgQh1hOohClYx38BHlq38Cv/bIOz/dq462pFDbAoGBAOcEkNUv1q2lHX8d6RH6QPoEri76Yhy2woWoukbkZeMsOvp6YbBUEjctK41NBHsk69W/1d3698HuFfW0hXsHkcBKyk21HHTA374KvgQiPqdNwcMXpWc6YmQIEzrOJZMP5dp2SXelSQiTBob7Ju/Zfxd3MPok9bO1LlqAG0AdDuMXAoGBAIa0cwyz6jcPq3bBuEeOki8zusmKWAcX5YNwJUN0JOnUD9AkQhOveEYXWstTwE7MZomWww4Uf5i+p67Upk+T6DO3yVjSuJKtLDOxGiBKxB4zDdtiT3uj0hAa6sfmDfDwPCW40QBQ185TWjMyi8J5mAopCRV8IA+eOH8Dvswn4euHAoGAcC33Zo5kYM3dFO0hUGmFQ+Mh8g4Dto3Ix763NdWS5E2GFjt3VHh+n+x/SY4srt+u5YzR/Yjw5msGntmaN7PlQssOkc1wlAFUpKPywW8fnX5UqLfCye2/+XMyY0vXUyJVK1BlPIQ2gsNiWAl9Ttr+rBZk4hMwfKNubuPmV6vEnuECgYEAo2AHJrLnJJ2TlS+gsjP9jOuAvDCVTVEnTd4qAlRH5jC/Dv8cUikJw492giGi9xXhGBb3W1CpJRGyBk/cWgpekbvrOzdWruLfoAfArUtQfDZjJN+Szi3qm6lqqoSUjiNdS6cK2EuJep+cBYxxIBcSWDvtMEZojYK1TnKTV9H2C6g=
      - Jwt__PublicKey=MIIBCgKCAQEAy3wuQ1UkUrcEaxR+1gVEEUigRdJthoFenMC/BhpB7y5pelrpoNxdHhAWDuHwOYvj70ZuRxlf2I5Gl+nuVTFQG0P7uS7coVT2zcrzBZp5WNs5LzWea2f5GyFOCtFeXH4fMqfIJdJs+y8+o2luQx4OdZkPJ9sTuRTywDEd92smwY0kqAtLa1ejuFmvB207qCJNKYgvYpgDXdYA5tgZxtepozTTbEBkYk14XETmK2GOgIR3B8PixfEFM2EK6oIqrtKEh020h1FiYVZNWlDmvpwWJxgNoaDoCvAay7jGDwn76Gu8rqTkkHaodNZ5QPasHuk6xqhnMCcYh2NBo9+rV290rQIDAQAB
    depends_on:
      postgres-auth:
        condition: service_healthy
    networks:
      - app-network

  postgres-document-analysis:
    image: postgres:15-alpine
    container_name: postgres-document-analysis
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: document_analysis_db
    volumes:
      - postgres_document_analysis_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-project:
    image: postgres:15-alpine
    container_name: postgres-project
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: projectsdb
    volumes:
      - postgres_project_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-backlog:
    image: postgres:15-alpine
    container_name: postgres-backlog
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: backlogdb
    volumes:
      - postgres_backlog_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  document-analysis-service:
    build:
      context: ../document-analysis-service
      dockerfile: Dockerfile
    container_name: document-analysis-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres-document-analysis:5432/document_analysis_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CONSUMER_GROUP=document-analysis-service
      - KAFKA_TOPIC_FILE_UPLOADED=file-uploaded
      - KAFKA_TOPIC_BACKLOG_READY=backlog-ready
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=documents
      - MINIO_SECURE=false
      - MISTRAL_API_KEY=bm7Pnu8yQAyyWdKbPv2mNyibNGXS4xfc
      - MISTRAL_AGENT_ID=ag_019b0f13cd877458a827a788e6857c60
      - MISTRAL_AGENT_TKP_ID=ag_019b0fcd619d7542b255b47153ab2d5b
      - SERVICE_NAME=document-analysis-service
      - LOG_LEVEL=INFO
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      postgres-document-analysis:
        condition: service_healthy
      kafka:
        condition: service_started
      minio:
        condition: service_started
    networks:
      - app-network

  project-service:
    build:
      context: ../ProjectService/ProjectService
      dockerfile: Dockerfile
    container_name: project-service
    ports:
      - "5159:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-project;Port=5432;Database=projectsdb;Username=postgres;Password=1234
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Issuer=AuthService
      - Jwt__Audience=ApiClients
      - Jwt__PublicKey=MIIBCgKCAQEAy3wuQ1UkUrcEaxR+1gVEEUigRdJthoFenMC/BhpB7y5pelrpoNxdHhAWDuHwOYvj70ZuRxlf2I5Gl+nuVTFQG0P7uS7coVT2zcrzBZp5WNs5LzWea2f5GyFOCtFeXH4fMqfIJdJs+y8+o2luQx4OdZkPJ9sTuRTywDEd92smwY0kqAtLa1ejuFmvB207qCJNKYgvYpgDXdYA5tgZxtepozTTbEBkYk14XETmK2GOgIR3B8PixfEFM2EK6oIqrtKEh020h1FiYVZNWlDmvpwWJxgNoaDoCvAay7jGDwn76Gu8rqTkkHaodNZ5QPasHuk6xqhnMCcYh2NBo9+rV290rQIDAQAB
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=documents
      - MINIO_SECURE=false
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_FILE_UPLOADED=file-uploaded
    depends_on:
      postgres-project:
        condition: service_healthy
      kafka:
        condition: service_started
      minio:
        condition: service_started
    networks:
      - app-network

  backlog-service:
    build:
      context: ../BacklogService
      dockerfile: Dockerfile
    container_name: backlog-service
    ports:
      - "5160:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres-backlog;Port=5432;Database=backlogdb;Username=postgres;Password=1234
      - ASPNETCORE_ENVIRONMENT=Development
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=documents
      - MINIO_SECURE=false
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC_BACKLOG_READY=backlog-ready
      - KAFKA_CONSUMER_GROUP=backlog-service
    depends_on:
      postgres-backlog:
        condition: service_healthy
      kafka:
        condition: service_started
      minio:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  postgres_auth_data:
  postgres_document_analysis_data:
  postgres_project_data:
  postgres_backlog_data:
  minio_data:

