version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: projectsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  projectservice:
    build:
      context: ./ProjectService
      dockerfile: Dockerfile
    ports:
      - "5159:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=projectsdb;Username=postgres;Password=1234
      - ASPNETCORE_ENVIRONMENT=Development
      - S3_SERVICE_URL=https://s3.yandexcloud.net
      - S3_REGION=ru-central1"
      - S3_ACCESS_KEY=ACCESSKEY
      - S3_SECRET_KEY=SECRETKEY
      - S3_BUCKET=projects
volumes:
  postgres_data:


